version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: govmesh_food_db
    environment:
      POSTGRES_DB: food_department_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./database/seed/seed_data.sql:/docker-entrypoint-initdb.d/01_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d food_department_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: govmesh_food_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/food_department_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      JWT_SECRET: GovMeshFoodDept2026SuperSecretKeyDepartment2Maharashtra2026
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: govmesh_food_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
